const { REGISTOR_SCHEMA, UPDATE_SCHEMA } = require('./users');
const {
  ENTRY_SCHEMA,
  OUT_SCHEMA,
  VISITORS_SCHEMA,
  AGGREGATE_SCHEMA
} = require('./visitor');

module.exports = {
  REGISTOR_SCHEMA,
  UPDATE_SCHEMA,
  ENTRY_SCHEMA,
  OUT_SCHEMA,
  VISITORS_SCHEMA,
  AGGREGATE_SCHEMA
};
